version: "3.1"  # Rasa version

language: "es"  # Language is Spanish

pipeline:
  # 1. Splits input into tokens based on whitespace.
  - name: WhitespaceTokenizer

  # 2. Extracts regex-based features (e.g., presence of digits, email, etc.)
  - name: RegexFeaturizer

  # 3. Uses a pre-trained transformer (BERT) to create deep language features.
  #    bert-base-multilingual-cased works for Spanish and many other languages.
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-multilingual-cased"

  # 4. Adds lexical and syntactic features like casing, POS tags, etc.
  - name: LexicalSyntacticFeaturizer

  # 5. Bag-of-words featurizer on words (helps capture word presence).
  - name: CountVectorsFeaturizer

  # 6. Character n-gram featurizer (captures subword information like misspellings).
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4

  # 7. Maps synonyms (e.g., "kg" → "kilogram").
  - name: EntitySynonymMapper

  # 8. Core NLU classifier that predicts intents and entities.
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true  # Helps avoid learning spurious similarities.

  # 9. Fallback mechanism when confidence is low.
  - name: FallbackClassifier
    threshold: 0.3  # If confidence < 0.3, fallback intent is triggered.

  # 10. Extracts entities like numbers, money, and time using Duckling.
  - name: DucklingEntityExtractor
    dimensions: ["number", "amount-of-money", "time"]
    locale: "es_ES"
    timezone: "America/Argentina/Buenos_Aires"
    anchor_date: "2023-01-01T12:00:00.000Z"  # Reference point for ambiguous dates

  # 11. Uses regex patterns and lookup tables for extracting entities.
  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true

# --- Dialogue Policies ---

policies:
  # Memorizes exact training stories.
  - name: MemoizationPolicy

  # Handles rule-based conversations.
  - name: RulePolicy

  # Uses deep learning to generalize dialog behavior.
  - name: TEDPolicy
    max_history: 10  # How many previous turns to consider
    epochs: 100      # Training iterations

# Optional assistant ID (not always needed unless you're using Rasa Pro)
assistant_id: 20250802-131303-coral-parent
