version: '3.9'

services:
  rasa:
    image: rasa/rasa:3.6.10
    container_name: rasa_server
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5005:5005"
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - action_server

  action_server:
    build:
      context: ./actions
      dockerfile: Dockerfile
    container_name: rasa_actions
    volumes:
      - .:/app
    working_dir: /app/actions
    ports:
      - "5055:5055"
