version: "3.9"

services:
  rasa:
    build:
      context: .
      target: rasa
    container_name: rasa_server
    volumes:
      - ./bot/data:/app/bot/data
      - ./bot/models:/app/bot/models
    ports:
      - "5005:5005"
    depends_on:
      - action_server

  action_server:
    build:
      context: .
      target: actions
    container_name: rasa_actions
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"

  trainer:
    build:
      context: .
      target: rasa
    container_name: rasa_trainer
    volumes:
      - ./bot/data:/app/bot/data
      - ./bot/models:/app/bot/models
    entrypoint: ["poetry", "run", "python", "entrenador/train.py"]
