version: "3.9"

services:
  rasa_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa_bot
    environment:
      - PORT=8000
      - ACTION_SERVER_URL=http://rasa_actions:5055/webhook
      - RASA_MODEL_PATH=models
    ports:
      - "8000:8000"
    volumes:
      # Monta carpetas específicas, no todo el directorio.
      # Esto evita que tu poetry.lock local sobreescriba al del contenedor.
      - ./bot:/app/bot
      - ./actions:/app/actions
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./models:/app/models
      # Añade cualquier otro archivo/carpeta que necesites editar en vivo
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
    # El comando ahora SÓLO ejecuta la aplicación
    command: poetry run manage bot

  rasa_actions:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa_actions
    environment:
      - PORT=5055
    ports:
      - "5055:5055"
    volumes:
      # Monta las mismas carpetas de código
      - ./bot:/app/bot
      - ./actions:/app/actions
      - ./scripts:/app/scripts
      - ./data:/app/data
      # Añade cualquier otro archivo/carpeta que necesites
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
    # El comando ahora SÓLO ejecuta la aplicación
    command: poetry run manage actions
