version: "3.9"

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Configuración para usar la GPU (como en tu archivo)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data: # Volumen para guardar los modelos de Ollama