version: "3.9"

services:
  rasa_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa_bot
    environment:
      - PORT=8000
      - ACTION_SERVER_URL=http://rasa_actions:5055/webhook
      - RASA_MODEL_PATH=models
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "poetry lock && poetry install && poetry run manage bot"

  rasa_actions:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa_actions
    environment:
      - PORT=5055
    ports:
      - "5055:5055"
    volumes:
      - .:/app
    command: sh -c "poetry lock && poetry install && poetry run manage actions"
 
