services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    container_name: rasa_server
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    working_dir: /app
    ports:
      - "5005:5005"
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - action_server

  action_server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    container_name: rasa_actions
    volumes:
      - ./actions:/app/actions
    working_dir: /app/actions
    ports:
      - "5055:5055"
