# Dockerfile.actions
FROM python:3.10-slim

WORKDIR /app

COPY actions/pyproject.toml actions/poetry.lock ./actions/
RUN pip install poetry && \
    cd actions && poetry install --no-root --no-dev

COPY actions /app/actions

WORKDIR /app/actions
CMD ["poetry", "run", "rasa", "run", "actions"]
