version: "1.0"

intents:
  - name: buscar_producto
    action: action_generica
    templates:
      - "{verbo} {producto}"
      - "{verbo} {producto} del proveedor {proveedor}"
      - "¿Tenés {producto} en categoría {categoria}?"
      - "Necesito {cantidad} de {producto}"
      - "Busco {producto} con {compuesto}"
      - "¿Cuánto cuesta {producto}?"
      - "¿Hay promociones para {producto} hasta el {fecha}?"
      - "Quiero {cantidad} unidades de {producto} del proveedor {proveedor}"
      - "{verbo} {producto} en categoría {categoria} con {compuesto}"
      - "Me interesa {producto}, ¿cuánto hay en stock?"

    entities:
      - producto
      - proveedor
      - cantidad
      - dosis
      - compuesto
      - categoria
      - fecha
      - cantidad_stock

  - name: buscar_oferta
    action: action_generica
    templates:
      - "¿Hay alguna {oferta} para {producto}?"
      - "Busco promociones con descuento de {cantidad_descuento}% en {producto}"
      - "Busco promociones con descuento de {cantidad_descuento}$ para {producto}"
      - "¿Qué {oferta} hay para {producto} de {proveedor}?"
      - "¿Tenés {producto} en oferta solo por el {dia}?"
      - "¿Cuál es la {oferta} de {producto} para hoy?"
      - "Busco {producto} con {cantidad_descuento}% de descuento del proveedor {proveedor}"
      - "¿Hay stock de {producto} en {oferta}?"
      - "Quiero conocer la {oferta} de {producto} hasta el {fecha}"
      - "¿Hay {oferta} de {producto} y {cantidad_stock} unidades disponibles?"

    entities:
      - producto
      - proveedor
      - categoria
      - dia
      - cantidad_descuento
      - cantidad_stock
      - fecha
      - oferta

  - name: fuera_aplicacion
    action: action_generica
    templates:
      - "Hola"
      - "Gracias por tu ayuda"
      - "¿Cómo estás?"
      - "¿Querés volver a productos y ofertas?"
      - "Buen día"
      - "Nos vemos luego"
      - "Gracias, hasta luego"

    entities: []

synonyms:
  verbo:
    - "mostrame"
    - "quiero ver"
    - "decime cuáles hay"
    - "enséñame"
    - "traeme"
    - "buscame"
  oferta:
    - "oferta"
    - "promoción"
    - "descuento"
    - "rebaja"
    - "rebaja especial"
  consulta:
    - "productos"
    - "medicamentos"
    - "lo que hay"
