version: '1.0'

# 🔹 Definición de intents
intents:
  saludo:
    tipo: ejemplos
    grupo: small_talk
    archivo: intents/saludo.yml
    action: action_smalltalk_situacion
    story_starter: true  # ✅ Puede iniciar conversación
    next_intents:
      - preguntar_como_estas
      - busqueda
      - pedir_chiste
      - despedida

  preguntar_como_estas:
    tipo: ejemplos
    grupo: small_talk
    archivo: intents/preguntar_cómo_estás.yml
    action: action_smalltalk_situacion
    story_starter: true  # ✅ Puede iniciar conversación
    next_intents:
      - responder_como_estoy
      - responder_estoy_bien
      - despedida


  responder_como_estoy:
    tipo: ejemplos
    grupo: small_talk
    archivo: intents/responder_como_estoy.yml
    action: action_smalltalk_situacion
    story_starter: false  # ❌ Solo respuesta a "preguntar_como_estas"
    next_intents:
      - busqueda
      - small_talk
      - despedida

  responder_estoy_bien:
    tipo: ejemplos
    grupo: small_talk
    archivo: intents/responder_estoy_bien.yml
    action: action_smalltalk_situacion
    story_starter: false  # ❌ Solo respuesta a "preguntar_como_estas"
    next_intents:
      - busqueda
      - small_talk
      - despedida

  despedida:
    tipo: ejemplos
    grupo: small_talk
    archivo: intents/despedida.yml
    action: action_smalltalk_situacion
    story_starter: true  # ✅ Puede iniciar conversación (usuario quiere terminar)
    next_intents: []

  pedir_chiste:
    tipo: ejemplos
    grupo: small_talk
    archivo: intents/pedir_chiste.yml
    action: action_smalltalk_situacion
    story_starter: true  # ✅ Puede iniciar conversación
    next_intents:
      - reirse_chiste
      - despedida
      - agradecer
      - small_talk

  reirse_chiste:
    tipo: ejemplos
    grupo: small_talk
    archivo: intents/reirse_chiste.yml
    action: action_smalltalk_situacion
    story_starter: false  # ❌ Solo respuesta a "pedir_chiste"
    next_intents:
      - busqueda
      - despedida
      - small_talk

  buscar_producto:
    tipo: template
    grupo: busqueda
    archivo: intents/buscar_producto.yml
    action: action_busqueda_situacion
    story_starter: true  # ✅ Puede iniciar conversación
    next_intents:
      - confirmacion
      - small_talk
      - despedida
      - completar_pedido

  buscar_oferta:
    tipo: template
    grupo: busqueda
    archivo: intents/buscar_oferta.yml
    action: action_busqueda_situacion
    story_starter: true  # ✅ Puede iniciar conversación
    next_intents:
      - afirmar
      - denegar
      - small_talk
      - despedida
      - completar_pedido

  completar_pedido:
    tipo: template
    grupo: busqueda
    archivo: intents/completar_pedido.yml
    action: action_busqueda_situacion
    story_starter: true  # ✅ Puede iniciar conversación (usuario ya sabe qué quiere)
    next_intents:
      - afirmar
      - denegar
      - small_talk
      - despedida
      - busqueda

  afirmar:
    tipo: ejemplos
    grupo: confirmacion
    archivo: intents/afirmar.yml
    action: action_conf_neg_agradecer
    story_starter: false  # ❌ Solo respuesta a confirmaciones
    next_intents:
      - busqueda
      - small_talk
      - despedida

  denegar:
    tipo: ejemplos
    grupo: negacion
    archivo: intents/denegar.yml
    action: action_conf_neg_agradecer
    story_starter: false  # ❌ Solo respuesta a confirmaciones
    next_intents:
      - busqueda
      - small_talk
      - despedida

  agradecimiento:
    tipo: ejemplos
    grupo: agradecimiento
    archivo: intents/agradecer.yml
    action: action_conf_neg_agradecer
    story_starter: false  # ❌ Solo respuesta a confirmaciones o a como se siente
    next_intents:
      - despedida
      - busqueda
      - small_talk

# 🔹 Sinónimos globales
synonyms: synonyms.yml

# 🔹 Fallback genérico
fallback:
  action: action_fallback_generico
  response: "Perdón, no entendí lo que quisiste decir."
  threshold: 0.6
  ambiguity_threshold: 0.15
