version: "1.0"

intents:
  - name: buscar_producto
    action: action_busqueda
    templates:
      - "{verbo} {producto}"
      - "{verbo} {producto} del proveedor {proveedor}"
      - "¿Tenés {producto} en categoría {categoria}?"
      - "Necesito {cantidad} de {producto}"
      - "Busco {producto} con {compuesto}"
      - "¿Cuánto cuesta {producto}?"
      - "¿Hay promociones para {producto} hasta el {fecha}?"
    entities:
      - producto
      - proveedor
      - cantidad
      - dosis
      - compuesto
      - categoria
      - fecha
      - dia
      - cantidad_stock
      - cantidad_descuento

  - name: buscar_oferta
    action: action_busqueda
    templates:
      - "¿Hay alguna {oferta} para {producto}?"
      - "Busco promociones con descuento {cantidad_descuento} en {producto}"
      - "¿Qué {oferta} hay para {producto} de {proveedor}?"
      - "¿Tenés {producto} en oferta solo por el {dia}?"
    entities:
      - producto
      - proveedor
      - categoria
      - dia
      - cantidad_descuento

  - name: fuera_aplicacion
    action: action_fuera_aplicacion
    templates:
      - "Hola"
      - "Gracias por tu ayuda"
      - "¿Cómo estás?"
      - "¿Querés volver a productos y ofertas?"
    entities: []

synonyms:
  verbo:
    - "mostrame"
    - "quiero ver"
    - "decime cuáles hay"
    - "enséñame"
  oferta:
    - "oferta"
    - "promoción"
    - "descuento"
    - "rebaja"
  consulta:
    - "productos"
    - "medicamentos"
    - "lo que hay"
