# entities_config.yml - Versión Refactorizada con Roles y Groups
version: "2.2"

# ===============================================================================  
# 🔹 CATEGORÍAS DE ENTIDADES  
# ===============================================================================  
entity_categories:
  business_core: "Entidades principales del negocio"
  filters: "Entidades para filtros y búsquedas"
  sentiment: "Entidades de sentimiento"
  system: "Entidades internas del agente"

# ===============================================================================  
# 🔹 PLANTILLAS DE CONFIGURACIÓN  
# ===============================================================================  
entity_templates:
  lookup_business: &lookup_business
    type: text
    lookup_table: true
    category: business_core

  static_filter: &static_filter
    type: text
    lookup_table: false
    pattern_source: "entidades.yml"
    category: filters

  dynamic_numeric: &dynamic_numeric
    type: text
    lookup_table: false
    pattern_source: "entidades_regex.yml"
    category: filters

  sentiment_entity: &sentiment_entity
    type: text
    lookup_table: false
    pattern_source: "entidades.yml"
    category: sentiment

# ===============================================================================  
# 🔹 DEFINICIÓN DE ENTIDADES CON ROLES Y GRUPOS  
# ===============================================================================  
entities:
  producto:
    <<: *static_filter
    roles: [search_primary, busqueda_core]
    groups: [promo1, promo2, promo3, cmp_quality, cmp_stock]

  proveedor:
    <<: *static_filter
    roles: [search_secondary]
    groups: [promo1, promo2]

  categoria:
    <<: *static_filter
    roles: [search_primary, filtro_taxonomia]
    groups: [promo3]

  ingrediente_activo:
    <<: *static_filter
    roles: [search_secondary, filtro_tecnico]
    groups: []

  animal:
    <<: *static_filter
    roles: [target_species, filtro_animal]
    groups: [filtro1]

  dosis:
    <<: *static_filter
    roles: [filtro_dosis]
    groups: [filtro1, promo2]

  sintoma:
    <<: *static_filter
    roles: [target_symptom, clinical_indicator]
    groups: [filtro_clinico]
    
  estado:
    <<: *static_filter
    roles: [filtro_estado]
    groups: [promo2]

  comparador:
    <<: *static_filter
    roles: [price_filter, quality, similarity, time_limit, discount_comparison]
    groups: [cmp_price, cmp_quality, cmp_stock]

  intencion_buscar:
    <<: *static_filter
    roles: [tipo_busqueda]
    groups: []

  tiempo:
    <<: *static_filter
    roles: [filtro_tiempo]
    values: [dia, fecha, indicador]
    groups: []

  cantidad:
    <<: *dynamic_numeric
    pattern: "cantidad_pattern"
    roles: [filtro_cantidad]
    groups: [cmp_stock]

  cantidad_stock:
    <<: *dynamic_numeric
    pattern: "cantidad_stock_pattern"
    roles: [filtro_inventario, availability_status, numeric_stock]
    groups: [cmp_stock, promo2]

  precio:
    <<: *dynamic_numeric
    pattern: "precio_pattern"
    roles: [filtro_precio, desde, hasta, descuento, bonificacion]
    groups: [cmp_price]

  cantidad_descuento:
    <<: *dynamic_numeric
    pattern: "cantidad_descuento_pattern"
    roles: [discount_rate, promotion_rate, baseline_discount, discount_percentage, minimum_discount, maximum_discount]
    groups: [promo1]

  cantidad_bonificacion:
    <<: *dynamic_numeric
    pattern: "cantidad_bonificacion_pattern"
    roles: [bonus_ratio, offer_type, percentage_bonus, minimum_bonus, maximum_bonus]
    groups: [promo3]

  fecha:
    <<: *static_filter
    roles: [expiry_date, availability_end, time_period]
    groups: [promo1]

  dia:
    <<: *static_filter
    roles: [ expiry_date]
    groups: [promo3]

  sentimiento:
    <<: *sentiment_entity
    values: [positivo, negativo, rechazo_total, solicitud_ayuda]
    roles: [sentiment_analysis]
    groups: []

# ===============================================================================  
# 🔹 ROLES Y AGRUPACIONES  
# ===============================================================================  
entity_roles:
  search_primary: [producto, proveedor, categoria]
  search_secondary: [ingrediente_activo, animal]
  filters_numeric: [cantidad, cantidad_stock, precio]
  filters_categorical: [estado, dosis, tiempo]
  comparison_filters: [comparador]
  sentiment_analysis: [sentimiento]

# ===============================================================================  
# 🔹 VALIDACIÓN Y CONSTRAINTS  
# ===============================================================================  
validation_rules:
  required_for_search: [producto, categoria]
  mutually_exclusive: 
    - [sentimiento:positivo, sentimiento:negativo]
    - [precio:descuento, precio:bonificacion]
  numeric_ranges:
    cantidad: {min: 1, max: 10000}
    cantidad_stock: {min: 0, max: 999999}
    precio: 
      desde: {min: 0, max: 999999}
      hasta: {min: 0, max: 999999}
      descuento: {min: 1, max: 100}
      bonificacion: {min: 1, max: 100}

# ===============================================================================  
# 🔹 CONFIGURACIÓN DE GENERACIÓN AUTOMÁTICA  
# ===============================================================================  
generation_config:
  auto_create_slots: true
  slot_template: "entity_slot"
  exclude_from_auto_slots: [sentimiento:solicitud_ayuda, sentimiento:rechazo_total]
