version: "3.1"

nlu:

# ---------------------------
# 🔹 SEGMENTOS DE CONVERSACIÓN
# ---------------------------
- synonym: inicio
  examples: |
    - hola
    - buenas
    - buen día
    - qué tal
    - cómo va
    - che
    - disculpá
    - perdón
    - buenos días
    - buenas tardes
    - buenas noches

- synonym: cierre_positivo
  examples: |
    - perfecto
    - genial
    - joya
    - bárbaro
    - excelente
    - de diez
    - impecable

- synonym: agradecimiento
  examples: |
    - gracias
    - muchas gracias
    - mil gracias
    - te agradezco
    - un millón de gracias

- synonym: solicitud_de_ayuda
  examples: |
    - me podrías ayudar
    - necesito
    - me das una mano
    - ayudame
    - dame una mano
    - me pasás
    - me mostrás
    - podrías decirme
    - me informás
    - me orientás
    - me guiás
    - me explicás

- synonym: duda
  examples: |
    - tenés idea
    - sabés si
    - che, sabés
    - por casualidad
    - te consulto
    - no estoy seguro
    - no sé si
    - será que
    - habrá
    - existirá
    - me pregunto si

- synonym: urgencia
  examples: |
    - urgente
    - lo necesito ya
    - apurate
    - es para hoy
    - cuanto antes
    - rápido
    - lo más pronto posible
    - me corre el tiempo
    - es importante
    - prioritario
    - inmediato

- synonym: muletilla
  examples: |
    - viste
    - entendés
    - digamos
    - ponele
    - o sea
    - bah
    - digo
    - tipo
    - como que
    - medio que
    - así como
    - capaz que

- synonym: afectivo
  examples: |
    - che
    - maestro
    - genio
    - loco
    - capo
    - máquina
    - crack
    - campeón
    - pibe
    - flaco
    - amigo
    - hermano

- synonym: comparativo
  examples: |
    - más barato
    - económico
    - rendidor
    - de mejor calidad
    - superior

- synonym: enfasis
  examples: |
    - por favor
    - sí o sí
    - urgente
    - re importante
    - necesito ya

- synonym: opcionalidad
  examples: |
    - si se puede
    - si tenés
    - de ser posible
    - cuando puedas
    - si es posible

- synonym: negacion
  examples: |
    - no quiero
    - sin
    - nada de
    - evitá
    - que no sea
