version: "2.0"

slot_templates:
  entity_slot: &entity_slot
    type: text
    influence_conversation: false
    mappings:
      - type: from_entity
        
  system_slot: &system_slot
    type: any
    influence_conversation: false
    mappings:
      - type: from_text
      
  categorical_engagement: &categorical_engagement
    type: categorical
    influence_conversation: false
    mappings:
      - type: from_entity

entity_slots:
  auto_generate: true
  source: "entities_config.yml"
  template: entity_slot
  exclude:
    - rechazo_total
    - solicitud_ayuda

system_slots:
  user_sentiment:
    type: categorical
    influence_conversation: false
    values: [positive, negative, neutral, rejection]
    initial_value: neutral
    mappings:
      - type: from_entity
        entity: user_sentiment
    
  last_intent_flow:
    type: text
    influence_conversation: false
    mappings:
      - type: from_text
    
  user_engagement_level:
    type: categorical
    influence_conversation: false
    values: [neutral, engaged, needs_help, confused, friendly, collaborative, 
             reset, disengaged, interested, needs_guidance, satisfied,
             awaiting_confirmation, awaiting_parameters]
    initial_value: neutral
    mappings:
      - type: from_entity
        entity: user_engagement_level

  pending_suggestion:
    type: any
    influence_conversation: false
    initial_value: null
    mappings:
      - type: from_text
    
  suggestion_context:
    type: any
    influence_conversation: false
    initial_value: null
    mappings:
      - type: from_text

  search_history:
    type: list
    influence_conversation: false
    initial_value: []
    mappings:
      - type: from_text
    
  context_decision_pending:
    type: bool
    influence_conversation: true
    initial_value: false
    mappings:
      - type: from_intent
        value: true
        intent: confirmar
      - type: from_intent
        value: false
        intent: denegar

  temp_entity_buffer:
    type: any
    influence_conversation: false
    initial_value: {}
    mappings:
      - type: from_text
    
  conversation_step:
    type: text
    influence_conversation: true
    initial_value: "inicio"
    mappings:
      - type: from_text

  search_active:
    type: bool
    influence_conversation: true
    initial_value: false
    mappings:
      - type: from_intent
        value: true
        intent: buscar_producto
      - type: from_intent
        value: false
        intent: fin_busqueda

  last_search_type:
    type: text
    influence_conversation: true
    initial_value: null
    mappings:
      - type: from_text

  search_results_count:
    type: float
    influence_conversation: false
    initial_value: null
    mappings:
      - type: from_text

slot_categories:
  conversation_control:
    slots: [user_sentiment, last_intent_flow, user_engagement_level, conversation_step]
    auto_reset_on_session: false
    
  suggestion_system:
    slots: [pending_suggestion, suggestion_context]
    auto_reset_on_session: false
    
  search_context:
    slots: [search_history, context_decision_pending, search_active, last_search_type, search_results_count]
    auto_reset_on_session: false
    
  temporary_processing:
    slots: [temp_entity_buffer]
    auto_reset_on_session: true

slot_management:
  reset_on_new_search:
    - temp_entity_buffer
    - pending_suggestion
    - suggestion_context
    - search_active
    
  session_persistent:
    - user_engagement_level
    - search_history
    - user_sentiment
    
  behavior_influencing:
    - user_sentiment
    - user_engagement_level
    - context_decision_pending
    - search_active
    
  size_limits:
    search_history: 10
    temp_entity_buffer: 50
    
  auto_cleanup:
    pending_suggestion: 3
    suggestion_context: 3
    temp_entity_buffer: 1
