# templates.yml - Templates por intent, con entities, roles y groups
version: "3.3"

# ======================================================================
# 🔹 TEMPLATES POR INTENT
# ======================================================================

basic_interaction:
  saludo:
    - "hola, ¿cómo estás {sentimiento:sentiment_analysis:core}?"
    - "buen día {sentimiento:sentiment_analysis:core}"
    - "qué tal {sentimiento:sentiment_analysis:core}?"
  
  despedida:
    - "chau {sentimiento:sentiment_analysis:core}"
    - "hasta luego {sentimiento:sentiment_analysis:core}"
    - "nos vemos {sentimiento:sentiment_analysis:core}"

  agradecer:
    - "gracias {sentimiento:sentiment_analysis:interaction}"
    - "muchas gracias {sentimiento:sentiment_analysis:interaction}"
    - "te lo agradezco {sentimiento:sentiment_analysis:interaction}"

  preguntar_como_estas:
    - "¿cómo estás {sentimiento:sentiment_analysis:smalltalk}?"
    - "qué tal {sentimiento:sentiment_analysis:smalltalk}?"

  responder_como_estoy:
    - "estoy bien {sentimiento:sentiment_analysis:smalltalk}"
    - "todo en orden {sentimiento:sentiment_analysis:smalltalk}"

  pedir_chiste:
    - "contame un chiste {sentimiento:sentiment_analysis:smalltalk}"
    - "haceme reír {sentimiento:sentiment_analysis:smalltalk}"

  reirse_chiste:
    - "jajaja {sentimiento:sentiment_analysis:smalltalk}"
    - "qué gracioso {sentimiento:sentiment_analysis:smalltalk}"

search_template:
  buscar_producto:
    - "quiero comprar {producto:search_primary:promo1}"
    - "me mostrás {producto:search_primary:promo2}?"
    - "{producto:search_primary:promo3} de {proveedor:search_secondary:promo1} hay en stock?"
    - "busco {producto:search_primary:promo1} de {proveedor:search_secondary:promo2} para {animal:target_species:filtro1}"
    - "necesito {producto:search_primary:promo2} en presentación {dosis:filters_categorical:filtro1}"
  
  buscar_oferta:
    - "qué ofertas hay de {producto:search_primary:promo1}?"
    - "hay descuentos en {proveedor:search_secondary:promo2}?"
    - "{producto:search_primary:promo2} con descuento de {cantidad_descuento:discount_rate:promo1}"
    - "promociones de {categoria:search_primary:promo3} con bonificación {cantidad_bonificacion:bonus_ratio:promo3}"

  consultar_novedades:
    - "qué novedades hay {indicador_temporal:filtro_tiempo}"
    - "productos nuevos de {proveedor:search_secondary:promo2}"
    - "qué ingresó {dia:arrival_date:promo3}"

  modificar_busqueda:
    - "mejor mostrame {producto:search_primary:promo2}"
    - "prefiero {producto:search_primary:promo3} en {dosis:filters_categorical:filtro1}"
    - "cambiá por algo {comparador:comparison_filters:cmp_price}"
    - "mejor movelo a {dia:arrival_date:promo3}"

confirmation_template:
  afirmar:
    - "sí, está bien {comparador:comparison_filters:cmp_quality} el anterior"
    - "perfecto, lo necesito para {dia:deadline:promo3}"
  
  denegar:
    - "no, prefiero otra cosa {comparador:comparison_filters:cmp_price}"
    - "no, mejor para {fecha:delivery_date:promo1}"

  completar_pedido:
    - "confirmo el pedido de {producto:search_primary:promo1}"
    - "listo, lo necesito para {dia:arrival_date:promo3}"
    - "dale, con el descuento de {cantidad_descuento:discount_rate:promo1}"
    - "confirmo para {animal:target_species:filtro1}"

fallback_template:
  off_topic:
    - "perdón, no entendí eso {sentimiento:sentiment_analysis:fallback}"
    - "no sé cómo responder {sentimiento:sentiment_analysis:fallback}"

  out_of_scope:
    - "eso está fuera de mi alcance"
    - "no puedo ayudarte con eso"

  ambiguity_fallback:
    - "no estoy seguro a qué te referís {sentimiento:sentiment_analysis:fallback}"
