# config.yml
version: "3.1"
language: "es"

pipeline:
  # === TOKENIZACIÓN ===
  - name: WhitespaceTokenizer
  
  # === EXTRACTORES (PRIMERO, antes de featurizers) ===
  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true
    case_sensitive: false
    use_word_boundaries: true
  
  # === FEATURIZERS ===
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  
  # ❌ ELIMINAR BERT (muy pesado para tu caso)
  # - name: LanguageModelFeaturizer
  #   model_name: "bert"
  #   model_weights: "bert-base-multilingual-cased"
  
  # === CLASIFICADORES ===
  - name: DIETClassifier
    epochs: 100              # ← Reducir a 100 (suficiente con buen regex)
    constrain_similarities: true
    entity_recognition: true
    intent_classification: true
    entity_roles: true       # ← CRÍTICO para tu domain
    entity_groups: true      # ← CRÍTICO para tu domain
    number_of_transformer_layers: 2
    transformer_size: 256
    BILOU_flag: true
    use_masked_language_model: false  # Sin BERT, no necesitas esto
  
  # === POST-PROCESAMIENTO ===
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50

# === POLICIES (DESCOMENTAR Y AJUSTAR) ===
policies:
  - name: MemoizationPolicy
    max_history: 3
  
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_fallback"
  
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 50
  
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

# === CONFIGURACIÓN ASISTENTE ===
assistant_id: pompi_v2