version: "3.1"

language: "es"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer

  # RegexEntityExtractor antes de DIET
  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true

  # Features de lenguaje profundo
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-multilingual-cased"

  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4

  - name: EntitySynonymMapper

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.3

  - name: DucklingEntityExtractor
    dimensions: ["number", "amount-of-money", "time"]
    locale: "es_ES"
    timezone: "America/Argentina/Buenos_Aires"
    anchor_date: "2023-01-01T12:00:00.000Z"

# --- Dialogue Policies ---

policies:
  # Memorizes exact training stories.
  - name: MemoizationPolicy

  # Handles rule-based conversations.
  - name: RulePolicy

  # Uses deep learning to generalize dialog behavior.
  - name: TEDPolicy
    max_history: 10  # How many previous turns to consider
    epochs: 100      # Training iterations

# Optional assistant ID (not always needed unless you're using Rasa Pro)
assistant_id: 20250802-131303-coral-parent

nlu:
  - data/nlu.yml
  - data/lookup_tables.yml
  - data/synonyms.yml
  - data/regex_entities.yml
stories:
  - data/stories.yml

rules:
  - data/rules.yml
