version: "3.1"

language: "es"

pipeline:
  # === TOKENIZACIÓN ===
- name: WhitespaceTokenizer

  # === FEATURIZERS ===
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-multilingual-cased"

  # === EXTRACTORES (ANTES de DIET) ===
- name: RegexEntityExtractor
  use_lookup_tables: true
  use_regexes: true
  case_sensitive: false
  use_word_boundaries: true

  # === CLASIFICADORES ===
- name: DIETClassifier
  epochs: 150    # ← Aumenta a 150-200 para mejor convergencia
  constrain_similarities: true
  entity_recognition: true
  intent_classification: true
  entity_roles: true
  number_of_transformer_layers: 2
  BILOU_flag: true    # ← Agrega esto para mejor detección de límites
  # === POST-PROCESAMIENTO ===
- name: EntitySynonymMapper



nlu:
- data/nlu.yml
- data/lookup_tables.yml
- data/synonyms.yml
- data/regex_entities.yml

stories:
- data/stories.yml

rules:
- data/rules.yml

# --- Bloque fallback personalizado para tu loader ---
fallback:
  action: action_fallback
  response: ""
  threshold: 0.6
  ambiguity_threshold: 0.15
assistant_id: 20250926-124303-roaring-mainmast
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
