version: "3.1"
language: "es"

pipeline:
  # === TOKENIZACIÓN ===
  - name: WhitespaceTokenizer

  # === FEATURIZERS ===
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4

    # === CLASIFICADORES ===
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: true
    entity_recognition: true
    role_recognition: true
    intent_classification: true
    entity_roles: true
    entity_groups: true
    number_of_transformer_layers: 2
    transformer_size: 256
    BILOU_flag: true
    use_masked_language_model: false
    number_of_negative_examples: 20
  
  # === EXTRACTORES ===
  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true
    case_sensitive: false
    use_word_boundaries: true
  
  
  

  
  # === POST-PROCESAMIENTO ===
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50

  # === FALLBACK DETECTOR (NLU) ===
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

# === POLICIES ===
policies:
  - name: MemoizationPolicy
    max_history: 3

  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true

  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 30

  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_fallback"
    enable_fallback_prediction: true   # 👈 clave para que se active automáticamente

# === CONFIGURACIÓN ASISTENTE ===
assistant_id: pompi_v2
