# ./actions/Dockerfile

FROM python:3.12-slim

RUN apt-get update && apt-get install -y build-essential curl

# Instala Poetry
ENV POETRY_VERSION=1.8.2
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

# Copiamos solo el archivo de dependencias (están en la raíz del proyecto)
COPY ../pyproject.toml ../poetry.lock* ./

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

# Ahora copiamos solo el código de las actions
COPY . /app/actions

EXPOSE 5055

CMD ["rasa", "run", "actions"]
